fix: changed from hardhat compile to foundry's

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -26,18 +26,24 @@ git add .
 # ---------------------------------------------------------------------------- #
 
 # ------------------------------ Natspec smells ------------------------------ #
-echo "👉 Checking for missing natspecs..."
-natspecSmellsOutput=$(npx @defi-wonderland/natspec-smells 2>&1)
-
-# Compare the trimmed output to "No issues found"
-if [ "$natspecSmellsOutput" != "No issues found" ]; then
-  echo "⛔️ Missing documentation or errors have been found:"
-  echo "$natspecSmellsOutput"
-  exit 1
+## check for env feature flag for natspec-smells. Default to true
+if [ "$SKIP_NATSPEC_SMELLS" = "true" ]; then
+  echo "👉 Skipping natspec-smells check..."
+  echo "✅ natspec-smells check skipped.\n"
+  exit 0
 else
-  echo "✅ No missing natspecs detected.\n"
-fi
+  echo "👉 Checking for missing natspecs..."
+  natspecSmellsOutput=$(npx @defi-wonderland/natspec-smells 2>&1)
 
+  # Compare the trimmed output to "No issues found"
+  if [ "$natspecSmellsOutput" != "No issues found" ]; then
+    echo "⛔️ Missing documentation or errors have been found:"
+    echo "$natspecSmellsOutput"
+    exit 1
+  else
+    echo "✅ No missing natspecs detected.\n"
+  fi
+fi
 # ------------------------------- Gas snapshot ------------------------------- #
 
 echo "👉 Checking gas snapshots..."
