feat: add natspec-smells in pre-commit hooks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -7,12 +7,35 @@
 
 # -------------------------- Foundry code formatting ------------------------- #
 
+# TODO: uncomment when the project as been migrate to foundry
+# echo "👉 Formatting code with Foundry..."
 # forge fmt
+# echo "✅ Code formatted with Foundry.\n\n"
 
 # ------------------------ Precompute Solidity Hashes ------------------------ #
-
+echo "👉 Precomputing Solidity hashes..."
 npx ts-node scripts/precompute-solidity-hashes.ts
+echo "✅ Solidity hashes precomputed.\n\n"
 
 # --------------------------- Add any changes made --------------------------- #
 
 git add .
+
+# ---------------------------------------------------------------------------- #
+#                                    Checks                                    #
+# ---------------------------------------------------------------------------- #
+
+# ------------------------------ Natspec smells ------------------------------ #
+echo "👉 Checking for missing natspecs..."
+natspecSmellsOutput=$(npx @defi-wonderland/natspec-smells 2>&1)
+
+# Compare the trimmed output to "No issues found"
+if [ "$natspecSmellsOutput" != "No issues found" ]; then
+  echo "⛔️ Missing documentation or errors have been found:"
+  echo "$natspecSmellsOutput"
+  exit 1
+else
+  echo "✅ No missing natspecs detected.\n"
+fi
+
+exit 0
