Remove husky hooks temporarily

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -27,27 +27,27 @@ echo "✅ Solidity hashes precomputed.\n\n"
 
 # ------------------------------ Natspec smells ------------------------------ #
 ## check for env feature flag for natspec-smells. Default to true
-if [ "$SKIP_NATSPEC_SMELLS" = "true" ]; then
-  echo "👉 Skipping natspec-smells check..."
-  echo "⛔️ WARNING: natspec-smells check has been skipped. THIS IS NOT THE RECOMMENDED PRACTICE."
+# if [ "$SKIP_NATSPEC_SMELLS" = "true" ]; then
+#   echo "👉 Skipping natspec-smells check..."
+#   echo "⛔️ WARNING: natspec-smells check has been skipped. THIS IS NOT THE RECOMMENDED PRACTICE."
 
-  exit 0
-else
-  echo "👉 Checking for missing natspecs..."
-  natspecSmellsOutput=$(npx @defi-wonderland/natspec-smells 2>&1)
+#   exit 0
+# else
+#   echo "👉 Checking for missing natspecs..."
+#   natspecSmellsOutput=$(npx @defi-wonderland/natspec-smells 2>&1)
 
-  # Compare the trimmed output to "No issues found"
-  if [ "$natspecSmellsOutput" != "No issues found" ]; then
-    echo "⛔️ Missing documentation or errors have been found:"
-    echo "$natspecSmellsOutput"
-    exit 1
-  else
-    echo "✅ No missing natspecs detected.\n"
-  fi
-fi
-# ------------------------------- Gas snapshot ------------------------------- #
+#   # Compare the trimmed output to "No issues found"
+#   if [ "$natspecSmellsOutput" != "No issues found" ]; then
+#     echo "⛔️ Missing documentation or errors have been found:"
+#     echo "$natspecSmellsOutput"
+#     exit 1
+#   else
+#     echo "✅ No missing natspecs detected.\n"
+#   fi
+# fi
+# # ------------------------------- Gas snapshot ------------------------------- #
 
-echo "👉 Checking gas snapshots..."
-npm run snapshot:check
-echo "✅ Gas snapshots are up to date.\n\n"
+# echo "👉 Checking gas snapshots..."
+# npm run snapshot:check
+# echo "✅ Gas snapshots are up to date.\n\n"
 
